### PR TITLE
Adding veroultra material

### PR DESCRIPTION
**Pull request by MeliTaliani**
As per title

### CODE REVIEW

**Comment by fiorisi** [comment]
cc @Mick3Lozzo

**Comment by Mick3Lozzo** [comment]
[mds_pj_veroultra-for-j55_0321b-1.pdf](https://github.com/user-attachments/files/17162090/mds_pj_veroultra-for-j55_0321b-1.pdf)

I verified the datasheet @MeliTaliani, and it seems fine to me. I can't find the Poisson's ratio value here.

image

Where have you found the Poisson coefficient? 0.33 is a reasonable value for VERO White and similar, but it is not easy to find on the Stratasys website. 

[0925-SupportingInformation.pdf](https://github.com/user-attachments/files/17162359/0925-SupportingInformation.pdf)

**Comment by MeliTaliani** [comment]
Yes @Mick3Lozzo, in the absence of an exact value from the VeroUltra datasheet, the value of Vero PureWhite was used. @Lawproto

**Comment by Mick3Lozzo** [comment]
https://arxiv.org/html/2407.08222v1

Here I found an article about the modelling of a soft finger manipulation robot.

_The robotic finger underwent one-shot 3D printing, where its CAD model was first sliced using GrabCAD. Next, the design was fabricated by the Stratasys J850 Polyjet printer, which seamlessly integrated markers into the process in a single step. The Polyjet printer ejected liquid photopolymer into the building tray with multiple heads, which were then solidified under ultraviolet light. No support structure was enabled during the printing for a fast prototype. A digital material with shore hardness 85A was selected by digitally mixing two raw materials: VeroUltra black and Agilus30 clear, whose material properties were determined using a uniaxial tensile test [[32](https://arxiv.org/html/2407.08222v1#bib.bib32)]. The properties of the material are such that Young’s modulus is E = 11.4 MPa and Poisson’s ratio is μ = 0.45._

Here I found another article that seems to confirm a greater value for the VeroUltra Poisson's ratio ➡️ μ = 0.41.

[Investigating the role of tesserae in energy absorption in shark.pdf](https://github.com/user-attachments/files/17162502/Investigating.the.role.of.tesserae.in.energy.absorption.in.shark.pdf)

image

**Comment by Lawproto** [comment]
Kudos to you for finding this, @Mick3Lozzo! 🎩 
μ = 0.41 and so be it, then.

@MeliTaliani can you please update the value accordingly?

**Review by Mick3Lozzo — COMMENTED** [review]
The Poisson's ratio should be 0.41

**Comment by MeliTaliani** [comment]
@Mick3Lozzo gentle ping for the review.

**Comment by Mick3Lozzo** [comment]
I re-checked, everything is fine @MeliTaliani.

**Pull request merged**
