### PR TITLE
Update bom_icub.fmt

### PR DESCRIPTION
**Pull request by salvi-mattia**
while we wait for the fix we came back to the previous versions of the bom fmt that works with wingst

### CODE REVIEW

**Review by fiorisi — APPROVED** [review]
@icub-tech-iit/silo-mech we revert this change until the next silo-meeting.

**Comment by Lawproto** [comment]
so, what is going on?

**Comment by fiorisi** [comment]
> so, what is going on?

Discussed F2F. Basically WINGST doesn't recognize the `COSM` category.

**Comment by Lawproto** [comment]
@salvi-mattia this has not been merged yet.

**Comment by pattacini** [comment]
> @salvi-mattia this has not been merged yet.

Usually, maintainers are responsible for merging the PR.
This can vary according to the specific policies anyhow.

@salvi-mattia is off 'till next Monday; don't know about @marcellosavoldi though.
@fiorisi, @Lawproto, you can merge it straight away, I think.

**Comment by Lawproto** [comment]
> Usually, maintainers are responsible for merging the PR.

@pattacini ah, we're fine then. @marcellosavoldi (the mantainer) is a renowned PR lover! 😃

**Pull request merged**
