### PR TITLE
Add coordinate system commercial: INTEL REALSENSE T265

### PR DESCRIPTION
**Pull request by FabioBergonti**
I added the pose frame as described in [this document](https://github.com/IntelRealSense/librealsense/blob/master/doc/t265.md)
image
image

### CODE REVIEW

**Comment by FabioBergonti** [comment]
image

**Comment by fiorisi** [comment]
Thanks @FabioBergonti!

Checking the model I noticed that the frame is not centered between the two cameras.

image
image

The POSE that you added corresponds to the center of tracking described [here](https://github.com/IntelRealSense/librealsense/blob/master/doc/t265.md#sensor-origin-and-coordinate-system)?

**Comment by FabioBergonti** [comment]
> The POSE that you added corresponds to the center of tracking described [here](https://github.com/IntelRealSense/librealsense/blob/master/doc/t265.md#sensor-origin-and-coordinate-system)?

Yes @fiorisi 
I can update the CAD placing the frame in between the two cameras

**Comment by FabioBergonti** [comment]
@fiorisi 
Fixed with https://github.com/icub-tech-iit/cad-libraries/pull/32/commits/9769db199a47b43bb29565504fe60baa11f43f8c
image

**Comment by fiorisi** [comment]
Great 🚀 

image
image

**Review by fiorisi — APPROVED** [review]

**Comment by fiorisi** [comment]
cc @icub-tech-iit/silo-mech

**Pull request merged**
