### PR TITLE
BOM quantity from integer to floating

### PR DESCRIPTION
**Pull request by Lawproto**
Preparing to deal with stuff-by-length in Creo.

### CODE REVIEW

**Comment by Lawproto** [comment]
@fiorisi I am available to do so. I suggest I create a fake assembly with the cable, do the BOM import in WinGST, verify quantity needed there and then proceed to delete the assembly.

@Fabrizio69 is this ok for you?

**Comment by Lawproto** [comment]
@fiorisi I did a test with an assembly, containing two cable cuts which are using the Ø0.81 Carlstahl steel cable.
immagine

This is the BOM output by Creo:
immagine

This is the result in WinGST after importing:
immagine
immagine

It seems pretty good to me!

**Review by fiorisi — APPROVED** [review]
Very good @Lawproto!
I approve the PR, let's only wait a positive feedback also from @Fabrizio69 before merging it.

**Comment by Fabrizio69** [comment]
> Very good @Lawproto! I approve the PR, let's only wait a positive feedback also from @Fabrizio69 before merging it.

Hi @Lawproto and @fiorisi, here is my positive feedback. Maybe I would dedicate a category just for tendons (instead of REWK).
I removed the codes used for test (cod.16956, 16957, 16958 and the BOMs with these codes).

**Comment by Lawproto** [comment]
@Fabrizio69 I would use the same category for the tendon sheaths and other possible future length based cuts. Let us choose wisely.

**Pull request merged**
